name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        - name: Checkmarx AST Github Action
          uses: Checkmarx/ast-github-action@2.0.23
          with:
            # Provide the AST portal URL
            base_uri: ${{secrets.CX_URL}}
            # Provide the Tenant for AST portal URL
            cx_tenant: ${{secrets.CX_TENANT}}
            # Client ID for AST portal authentication
            cx_client_id: ${{secrets.CX_CLIENT_ID}}
            # Secret key for AST portal authentication
            cx_client_secret: ${{secrets.CX_CLIENT_SECRET}}
            # Select a Checkmarx Project Name
            project_name: ${{github.repository}}
            # Branch name
            branch: # optional, default is ${{ github.head_ref || github.ref }}
#            additional_params:
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: cx_result.sarif
      
      
##########################################################################################################################################      
#      - name: Download SCA Resolver
#        run: |
#          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
#          tar -xzvf ScaResolver-linux64.tar.gz
#          rm -rf ScaResolver-linux64.tar.gz
#
#      - name: Install Maven, NPM, ... # Add any necessary package management
#        run: |
#          sudo apt install maven npm
#
#      - name: Run Checkmarx One CLI Scan
#        run: |
#          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#          /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
#          /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
#            scan create \
#            -s . \
#            --agent GitHub \
#            --project-name ${{ github.repository }} \
#            --branch ${GITHUB_REF##*/} \
#            --base-uri ${{ secrets.CX_BASE_URI }} \
#            --tenant ${{ secrets.CX_TENANT }} \
#            --client-id ${{ secrets.CX_CLIENT_ID }} \
#            --client-secret ${{ secrets.CX_CLIENT_SECRET }} \
#            --sca-resolver ./ScaResolver
##########################################################################################################################################
